language: android

android:
  components:
    - build-tools-21.1.1
    - android-18
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email: true

sudo: false